// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCollectionsParams creates a new GetCollectionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCollectionsParams() *GetCollectionsParams {
	return &GetCollectionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCollectionsParamsWithTimeout creates a new GetCollectionsParams object
// with the ability to set a timeout on a request.
func NewGetCollectionsParamsWithTimeout(timeout time.Duration) *GetCollectionsParams {
	return &GetCollectionsParams{
		timeout: timeout,
	}
}

// NewGetCollectionsParamsWithContext creates a new GetCollectionsParams object
// with the ability to set a context for a request.
func NewGetCollectionsParamsWithContext(ctx context.Context) *GetCollectionsParams {
	return &GetCollectionsParams{
		Context: ctx,
	}
}

// NewGetCollectionsParamsWithHTTPClient creates a new GetCollectionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCollectionsParamsWithHTTPClient(client *http.Client) *GetCollectionsParams {
	return &GetCollectionsParams{
		HTTPClient: client,
	}
}

/* GetCollectionsParams contains all the parameters to send to the API endpoint
   for the get collections operation.

   Typically these are written to a http.Request.
*/
type GetCollectionsParams struct {

	/* Page.

	   Page number. Default is 1
	*/
	Page *string

	/* PerPage.

	   Number of results per page. Default is 20
	*/
	PerPage *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get collections params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollectionsParams) WithDefaults() *GetCollectionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get collections params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollectionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get collections params
func (o *GetCollectionsParams) WithTimeout(timeout time.Duration) *GetCollectionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get collections params
func (o *GetCollectionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get collections params
func (o *GetCollectionsParams) WithContext(ctx context.Context) *GetCollectionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get collections params
func (o *GetCollectionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get collections params
func (o *GetCollectionsParams) WithHTTPClient(client *http.Client) *GetCollectionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get collections params
func (o *GetCollectionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPage adds the page to the get collections params
func (o *GetCollectionsParams) WithPage(page *string) *GetCollectionsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get collections params
func (o *GetCollectionsParams) SetPage(page *string) {
	o.Page = page
}

// WithPerPage adds the perPage to the get collections params
func (o *GetCollectionsParams) WithPerPage(perPage *string) *GetCollectionsParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get collections params
func (o *GetCollectionsParams) SetPerPage(perPage *string) {
	o.PerPage = perPage
}

// WriteToRequest writes these params to a swagger request
func (o *GetCollectionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Page != nil {

		// query param page
		var qrPage string

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := qrPage
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PerPage != nil {

		// query param per_page
		var qrPerPage string

		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := qrPerPage
		if qPerPage != "" {

			if err := r.SetQueryParam("per_page", qPerPage); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
