// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCollectionsCollectionIDParams creates a new GetCollectionsCollectionIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCollectionsCollectionIDParams() *GetCollectionsCollectionIDParams {
	return &GetCollectionsCollectionIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCollectionsCollectionIDParamsWithTimeout creates a new GetCollectionsCollectionIDParams object
// with the ability to set a timeout on a request.
func NewGetCollectionsCollectionIDParamsWithTimeout(timeout time.Duration) *GetCollectionsCollectionIDParams {
	return &GetCollectionsCollectionIDParams{
		timeout: timeout,
	}
}

// NewGetCollectionsCollectionIDParamsWithContext creates a new GetCollectionsCollectionIDParams object
// with the ability to set a context for a request.
func NewGetCollectionsCollectionIDParamsWithContext(ctx context.Context) *GetCollectionsCollectionIDParams {
	return &GetCollectionsCollectionIDParams{
		Context: ctx,
	}
}

// NewGetCollectionsCollectionIDParamsWithHTTPClient creates a new GetCollectionsCollectionIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCollectionsCollectionIDParamsWithHTTPClient(client *http.Client) *GetCollectionsCollectionIDParams {
	return &GetCollectionsCollectionIDParams{
		HTTPClient: client,
	}
}

/* GetCollectionsCollectionIDParams contains all the parameters to send to the API endpoint
   for the get collections collection ID operation.

   Typically these are written to a http.Request.
*/
type GetCollectionsCollectionIDParams struct {

	/* CollectionID.

	   The collection identifier number
	*/
	CollectionID string

	/* Page.

	   Page number. Default is 1
	*/
	Page *string

	/* PerPage.

	   Number of results per page. Default is 20
	*/
	PerPage *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get collections collection ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollectionsCollectionIDParams) WithDefaults() *GetCollectionsCollectionIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get collections collection ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollectionsCollectionIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get collections collection ID params
func (o *GetCollectionsCollectionIDParams) WithTimeout(timeout time.Duration) *GetCollectionsCollectionIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get collections collection ID params
func (o *GetCollectionsCollectionIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get collections collection ID params
func (o *GetCollectionsCollectionIDParams) WithContext(ctx context.Context) *GetCollectionsCollectionIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get collections collection ID params
func (o *GetCollectionsCollectionIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get collections collection ID params
func (o *GetCollectionsCollectionIDParams) WithHTTPClient(client *http.Client) *GetCollectionsCollectionIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get collections collection ID params
func (o *GetCollectionsCollectionIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCollectionID adds the collectionID to the get collections collection ID params
func (o *GetCollectionsCollectionIDParams) WithCollectionID(collectionID string) *GetCollectionsCollectionIDParams {
	o.SetCollectionID(collectionID)
	return o
}

// SetCollectionID adds the collectionId to the get collections collection ID params
func (o *GetCollectionsCollectionIDParams) SetCollectionID(collectionID string) {
	o.CollectionID = collectionID
}

// WithPage adds the page to the get collections collection ID params
func (o *GetCollectionsCollectionIDParams) WithPage(page *string) *GetCollectionsCollectionIDParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get collections collection ID params
func (o *GetCollectionsCollectionIDParams) SetPage(page *string) {
	o.Page = page
}

// WithPerPage adds the perPage to the get collections collection ID params
func (o *GetCollectionsCollectionIDParams) WithPerPage(perPage *string) *GetCollectionsCollectionIDParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get collections collection ID params
func (o *GetCollectionsCollectionIDParams) SetPerPage(perPage *string) {
	o.PerPage = perPage
}

// WriteToRequest writes these params to a swagger request
func (o *GetCollectionsCollectionIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param collection_id
	if err := r.SetPathParam("collection_id", o.CollectionID); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage string

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := qrPage
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PerPage != nil {

		// query param per_page
		var qrPerPage string

		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := qrPerPage
		if qPerPage != "" {

			if err := r.SetQueryParam("per_page", qPerPage); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
