// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/justprintit/mmf/swagger/models"
)

// GetCollectionsCollectionIDReader is a Reader for the GetCollectionsCollectionID structure.
type GetCollectionsCollectionIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCollectionsCollectionIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCollectionsCollectionIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCollectionsCollectionIDOK creates a GetCollectionsCollectionIDOK with default headers values
func NewGetCollectionsCollectionIDOK() *GetCollectionsCollectionIDOK {
	return &GetCollectionsCollectionIDOK{}
}

/* GetCollectionsCollectionIDOK describes a response with status code 200, with default header values.

The collection information and its objects
*/
type GetCollectionsCollectionIDOK struct {
	Payload *models.Collection
}

func (o *GetCollectionsCollectionIDOK) Error() string {
	return fmt.Sprintf("[GET /collections/{collection_id}][%d] getCollectionsCollectionIdOK  %+v", 200, o.Payload)
}
func (o *GetCollectionsCollectionIDOK) GetPayload() *models.Collection {
	return o.Payload
}

func (o *GetCollectionsCollectionIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Collection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
