// Code generated by go-swagger; DO NOT EDIT.

package objects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/justprintit/mmf/swagger/models"
)

// GetObjectsObjectIDUploadStatusReader is a Reader for the GetObjectsObjectIDUploadStatus structure.
type GetObjectsObjectIDUploadStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetObjectsObjectIDUploadStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetObjectsObjectIDUploadStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetObjectsObjectIDUploadStatusOK creates a GetObjectsObjectIDUploadStatusOK with default headers values
func NewGetObjectsObjectIDUploadStatusOK() *GetObjectsObjectIDUploadStatusOK {
	return &GetObjectsObjectIDUploadStatusOK{}
}

/* GetObjectsObjectIDUploadStatusOK describes a response with status code 200, with default header values.

Object
*/
type GetObjectsObjectIDUploadStatusOK struct {
	Payload *models.ObjectUploadStatus
}

func (o *GetObjectsObjectIDUploadStatusOK) Error() string {
	return fmt.Sprintf("[GET /objects/{object_id}/upload_status][%d] getObjectsObjectIdUploadStatusOK  %+v", 200, o.Payload)
}
func (o *GetObjectsObjectIDUploadStatusOK) GetPayload() *models.ObjectUploadStatus {
	return o.Payload
}

func (o *GetObjectsObjectIDUploadStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ObjectUploadStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
