// Code generated by go-swagger; DO NOT EDIT.

package objects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetObjectsObjectIDUploadStatusParams creates a new GetObjectsObjectIDUploadStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetObjectsObjectIDUploadStatusParams() *GetObjectsObjectIDUploadStatusParams {
	return &GetObjectsObjectIDUploadStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetObjectsObjectIDUploadStatusParamsWithTimeout creates a new GetObjectsObjectIDUploadStatusParams object
// with the ability to set a timeout on a request.
func NewGetObjectsObjectIDUploadStatusParamsWithTimeout(timeout time.Duration) *GetObjectsObjectIDUploadStatusParams {
	return &GetObjectsObjectIDUploadStatusParams{
		timeout: timeout,
	}
}

// NewGetObjectsObjectIDUploadStatusParamsWithContext creates a new GetObjectsObjectIDUploadStatusParams object
// with the ability to set a context for a request.
func NewGetObjectsObjectIDUploadStatusParamsWithContext(ctx context.Context) *GetObjectsObjectIDUploadStatusParams {
	return &GetObjectsObjectIDUploadStatusParams{
		Context: ctx,
	}
}

// NewGetObjectsObjectIDUploadStatusParamsWithHTTPClient creates a new GetObjectsObjectIDUploadStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetObjectsObjectIDUploadStatusParamsWithHTTPClient(client *http.Client) *GetObjectsObjectIDUploadStatusParams {
	return &GetObjectsObjectIDUploadStatusParams{
		HTTPClient: client,
	}
}

/* GetObjectsObjectIDUploadStatusParams contains all the parameters to send to the API endpoint
   for the get objects object ID upload status operation.

   Typically these are written to a http.Request.
*/
type GetObjectsObjectIDUploadStatusParams struct {

	/* ObjectID.

	   The object identifier number
	*/
	ObjectID float64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get objects object ID upload status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetObjectsObjectIDUploadStatusParams) WithDefaults() *GetObjectsObjectIDUploadStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get objects object ID upload status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetObjectsObjectIDUploadStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get objects object ID upload status params
func (o *GetObjectsObjectIDUploadStatusParams) WithTimeout(timeout time.Duration) *GetObjectsObjectIDUploadStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get objects object ID upload status params
func (o *GetObjectsObjectIDUploadStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get objects object ID upload status params
func (o *GetObjectsObjectIDUploadStatusParams) WithContext(ctx context.Context) *GetObjectsObjectIDUploadStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get objects object ID upload status params
func (o *GetObjectsObjectIDUploadStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get objects object ID upload status params
func (o *GetObjectsObjectIDUploadStatusParams) WithHTTPClient(client *http.Client) *GetObjectsObjectIDUploadStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get objects object ID upload status params
func (o *GetObjectsObjectIDUploadStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithObjectID adds the objectID to the get objects object ID upload status params
func (o *GetObjectsObjectIDUploadStatusParams) WithObjectID(objectID float64) *GetObjectsObjectIDUploadStatusParams {
	o.SetObjectID(objectID)
	return o
}

// SetObjectID adds the objectId to the get objects object ID upload status params
func (o *GetObjectsObjectIDUploadStatusParams) SetObjectID(objectID float64) {
	o.ObjectID = objectID
}

// WriteToRequest writes these params to a swagger request
func (o *GetObjectsObjectIDUploadStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param object_id
	if err := r.SetPathParam("object_id", swag.FormatFloat64(o.ObjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
