// Code generated by go-swagger; DO NOT EDIT.

package objects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/justprintit/mmf/swagger/models"
)

// NewPostObjectParams creates a new PostObjectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostObjectParams() *PostObjectParams {
	return &PostObjectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostObjectParamsWithTimeout creates a new PostObjectParams object
// with the ability to set a timeout on a request.
func NewPostObjectParamsWithTimeout(timeout time.Duration) *PostObjectParams {
	return &PostObjectParams{
		timeout: timeout,
	}
}

// NewPostObjectParamsWithContext creates a new PostObjectParams object
// with the ability to set a context for a request.
func NewPostObjectParamsWithContext(ctx context.Context) *PostObjectParams {
	return &PostObjectParams{
		Context: ctx,
	}
}

// NewPostObjectParamsWithHTTPClient creates a new PostObjectParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostObjectParamsWithHTTPClient(client *http.Client) *PostObjectParams {
	return &PostObjectParams{
		HTTPClient: client,
	}
}

/* PostObjectParams contains all the parameters to send to the API endpoint
   for the post object operation.

   Typically these are written to a http.Request.
*/
type PostObjectParams struct {

	/* Metadata.

	   Metadata for submitting a for object
	*/
	Metadata *models.ObjectMetadata

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post object params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostObjectParams) WithDefaults() *PostObjectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post object params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostObjectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post object params
func (o *PostObjectParams) WithTimeout(timeout time.Duration) *PostObjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post object params
func (o *PostObjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post object params
func (o *PostObjectParams) WithContext(ctx context.Context) *PostObjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post object params
func (o *PostObjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post object params
func (o *PostObjectParams) WithHTTPClient(client *http.Client) *PostObjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post object params
func (o *PostObjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMetadata adds the metadata to the post object params
func (o *PostObjectParams) WithMetadata(metadata *models.ObjectMetadata) *PostObjectParams {
	o.SetMetadata(metadata)
	return o
}

// SetMetadata adds the metadata to the post object params
func (o *PostObjectParams) SetMetadata(metadata *models.ObjectMetadata) {
	o.Metadata = metadata
}

// WriteToRequest writes these params to a swagger request
func (o *PostObjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Metadata != nil {
		if err := r.SetBodyParam(o.Metadata); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
