// Code generated by go-swagger; DO NOT EDIT.

package categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/justprintit/mmf/swagger/models"
)

// GetCategoriesCategoryIDReader is a Reader for the GetCategoriesCategoryID structure.
type GetCategoriesCategoryIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCategoriesCategoryIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCategoriesCategoryIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCategoriesCategoryIDOK creates a GetCategoriesCategoryIDOK with default headers values
func NewGetCategoriesCategoryIDOK() *GetCategoriesCategoryIDOK {
	return &GetCategoriesCategoryIDOK{}
}

/* GetCategoriesCategoryIDOK describes a response with status code 200, with default header values.

The category information and its children
*/
type GetCategoriesCategoryIDOK struct {
	Payload *models.Category
}

func (o *GetCategoriesCategoryIDOK) Error() string {
	return fmt.Sprintf("[GET /categories/{category_id}][%d] getCategoriesCategoryIdOK  %+v", 200, o.Payload)
}
func (o *GetCategoriesCategoryIDOK) GetPayload() *models.Category {
	return o.Payload
}

func (o *GetCategoriesCategoryIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Category)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
