// Code generated by go-swagger; DO NOT EDIT.

package categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCategoriesCategoryIDParams creates a new GetCategoriesCategoryIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCategoriesCategoryIDParams() *GetCategoriesCategoryIDParams {
	return &GetCategoriesCategoryIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCategoriesCategoryIDParamsWithTimeout creates a new GetCategoriesCategoryIDParams object
// with the ability to set a timeout on a request.
func NewGetCategoriesCategoryIDParamsWithTimeout(timeout time.Duration) *GetCategoriesCategoryIDParams {
	return &GetCategoriesCategoryIDParams{
		timeout: timeout,
	}
}

// NewGetCategoriesCategoryIDParamsWithContext creates a new GetCategoriesCategoryIDParams object
// with the ability to set a context for a request.
func NewGetCategoriesCategoryIDParamsWithContext(ctx context.Context) *GetCategoriesCategoryIDParams {
	return &GetCategoriesCategoryIDParams{
		Context: ctx,
	}
}

// NewGetCategoriesCategoryIDParamsWithHTTPClient creates a new GetCategoriesCategoryIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCategoriesCategoryIDParamsWithHTTPClient(client *http.Client) *GetCategoriesCategoryIDParams {
	return &GetCategoriesCategoryIDParams{
		HTTPClient: client,
	}
}

/* GetCategoriesCategoryIDParams contains all the parameters to send to the API endpoint
   for the get categories category ID operation.

   Typically these are written to a http.Request.
*/
type GetCategoriesCategoryIDParams struct {

	/* CategoryID.

	   The category identifier number
	*/
	CategoryID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get categories category ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCategoriesCategoryIDParams) WithDefaults() *GetCategoriesCategoryIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get categories category ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCategoriesCategoryIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get categories category ID params
func (o *GetCategoriesCategoryIDParams) WithTimeout(timeout time.Duration) *GetCategoriesCategoryIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get categories category ID params
func (o *GetCategoriesCategoryIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get categories category ID params
func (o *GetCategoriesCategoryIDParams) WithContext(ctx context.Context) *GetCategoriesCategoryIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get categories category ID params
func (o *GetCategoriesCategoryIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get categories category ID params
func (o *GetCategoriesCategoryIDParams) WithHTTPClient(client *http.Client) *GetCategoriesCategoryIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get categories category ID params
func (o *GetCategoriesCategoryIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCategoryID adds the categoryID to the get categories category ID params
func (o *GetCategoriesCategoryIDParams) WithCategoryID(categoryID string) *GetCategoriesCategoryIDParams {
	o.SetCategoryID(categoryID)
	return o
}

// SetCategoryID adds the categoryId to the get categories category ID params
func (o *GetCategoriesCategoryIDParams) SetCategoryID(categoryID string) {
	o.CategoryID = categoryID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCategoriesCategoryIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param category_id
	if err := r.SetPathParam("category_id", o.CategoryID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
