// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/justprintit/mmf/swagger/client/categories"
	"github.com/justprintit/mmf/swagger/client/collections"
	"github.com/justprintit/mmf/swagger/client/files"
	"github.com/justprintit/mmf/swagger/client/objects"
	"github.com/justprintit/mmf/swagger/client/search"
	"github.com/justprintit/mmf/swagger/client/users"
)

// Default my mini factory API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "www.myminifactory.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api/v2"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new my mini factory API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *MyMiniFactoryAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new my mini factory API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *MyMiniFactoryAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new my mini factory API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *MyMiniFactoryAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(MyMiniFactoryAPI)
	cli.Transport = transport
	cli.Categories = categories.New(transport, formats)
	cli.Collections = collections.New(transport, formats)
	cli.Files = files.New(transport, formats)
	cli.Objects = objects.New(transport, formats)
	cli.Search = search.New(transport, formats)
	cli.Users = users.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// MyMiniFactoryAPI is a client for my mini factory API
type MyMiniFactoryAPI struct {
	Categories categories.ClientService

	Collections collections.ClientService

	Files files.ClientService

	Objects objects.ClientService

	Search search.ClientService

	Users users.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *MyMiniFactoryAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Categories.SetTransport(transport)
	c.Collections.SetTransport(transport)
	c.Files.SetTransport(transport)
	c.Objects.SetTransport(transport)
	c.Search.SetTransport(transport)
	c.Users.SetTransport(transport)
}
