// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUsersUsernameObjectsParams creates a new GetUsersUsernameObjectsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUsersUsernameObjectsParams() *GetUsersUsernameObjectsParams {
	return &GetUsersUsernameObjectsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUsersUsernameObjectsParamsWithTimeout creates a new GetUsersUsernameObjectsParams object
// with the ability to set a timeout on a request.
func NewGetUsersUsernameObjectsParamsWithTimeout(timeout time.Duration) *GetUsersUsernameObjectsParams {
	return &GetUsersUsernameObjectsParams{
		timeout: timeout,
	}
}

// NewGetUsersUsernameObjectsParamsWithContext creates a new GetUsersUsernameObjectsParams object
// with the ability to set a context for a request.
func NewGetUsersUsernameObjectsParamsWithContext(ctx context.Context) *GetUsersUsernameObjectsParams {
	return &GetUsersUsernameObjectsParams{
		Context: ctx,
	}
}

// NewGetUsersUsernameObjectsParamsWithHTTPClient creates a new GetUsersUsernameObjectsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUsersUsernameObjectsParamsWithHTTPClient(client *http.Client) *GetUsersUsernameObjectsParams {
	return &GetUsersUsernameObjectsParams{
		HTTPClient: client,
	}
}

/* GetUsersUsernameObjectsParams contains all the parameters to send to the API endpoint
   for the get users username objects operation.

   Typically these are written to a http.Request.
*/
type GetUsersUsernameObjectsParams struct {

	/* Page.

	   Page number. Default is 1
	*/
	Page *string

	/* PerPage.

	   Number of results per page. Default is 20
	*/
	PerPage *string

	/* Username.

	   The user's username
	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get users username objects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUsersUsernameObjectsParams) WithDefaults() *GetUsersUsernameObjectsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get users username objects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUsersUsernameObjectsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get users username objects params
func (o *GetUsersUsernameObjectsParams) WithTimeout(timeout time.Duration) *GetUsersUsernameObjectsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get users username objects params
func (o *GetUsersUsernameObjectsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get users username objects params
func (o *GetUsersUsernameObjectsParams) WithContext(ctx context.Context) *GetUsersUsernameObjectsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get users username objects params
func (o *GetUsersUsernameObjectsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get users username objects params
func (o *GetUsersUsernameObjectsParams) WithHTTPClient(client *http.Client) *GetUsersUsernameObjectsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get users username objects params
func (o *GetUsersUsernameObjectsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPage adds the page to the get users username objects params
func (o *GetUsersUsernameObjectsParams) WithPage(page *string) *GetUsersUsernameObjectsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get users username objects params
func (o *GetUsersUsernameObjectsParams) SetPage(page *string) {
	o.Page = page
}

// WithPerPage adds the perPage to the get users username objects params
func (o *GetUsersUsernameObjectsParams) WithPerPage(perPage *string) *GetUsersUsernameObjectsParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get users username objects params
func (o *GetUsersUsernameObjectsParams) SetPerPage(perPage *string) {
	o.PerPage = perPage
}

// WithUsername adds the username to the get users username objects params
func (o *GetUsersUsernameObjectsParams) WithUsername(username string) *GetUsersUsernameObjectsParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the get users username objects params
func (o *GetUsersUsernameObjectsParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *GetUsersUsernameObjectsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Page != nil {

		// query param page
		var qrPage string

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := qrPage
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PerPage != nil {

		// query param per_page
		var qrPerPage string

		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := qrPerPage
		if qPerPage != "" {

			if err := r.SetQueryParam("per_page", qPerPage); err != nil {
				return err
			}
		}
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
