// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/justprintit/mmf/swagger/models"
)

// GetUsersUsernameCollectionsCollectionSlugReader is a Reader for the GetUsersUsernameCollectionsCollectionSlug structure.
type GetUsersUsernameCollectionsCollectionSlugReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUsersUsernameCollectionsCollectionSlugReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUsersUsernameCollectionsCollectionSlugOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetUsersUsernameCollectionsCollectionSlugOK creates a GetUsersUsernameCollectionsCollectionSlugOK with default headers values
func NewGetUsersUsernameCollectionsCollectionSlugOK() *GetUsersUsernameCollectionsCollectionSlugOK {
	return &GetUsersUsernameCollectionsCollectionSlugOK{}
}

/* GetUsersUsernameCollectionsCollectionSlugOK describes a response with status code 200, with default header values.

The collection information and its objects
*/
type GetUsersUsernameCollectionsCollectionSlugOK struct {
	Payload *models.Collection
}

func (o *GetUsersUsernameCollectionsCollectionSlugOK) Error() string {
	return fmt.Sprintf("[GET /users/{username}/collections/{collection_slug}][%d] getUsersUsernameCollectionsCollectionSlugOK  %+v", 200, o.Payload)
}
func (o *GetUsersUsernameCollectionsCollectionSlugOK) GetPayload() *models.Collection {
	return o.Payload
}

func (o *GetUsersUsernameCollectionsCollectionSlugOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Collection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
