// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUsersUsernameCollectionsCollectionSlugParams creates a new GetUsersUsernameCollectionsCollectionSlugParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUsersUsernameCollectionsCollectionSlugParams() *GetUsersUsernameCollectionsCollectionSlugParams {
	return &GetUsersUsernameCollectionsCollectionSlugParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUsersUsernameCollectionsCollectionSlugParamsWithTimeout creates a new GetUsersUsernameCollectionsCollectionSlugParams object
// with the ability to set a timeout on a request.
func NewGetUsersUsernameCollectionsCollectionSlugParamsWithTimeout(timeout time.Duration) *GetUsersUsernameCollectionsCollectionSlugParams {
	return &GetUsersUsernameCollectionsCollectionSlugParams{
		timeout: timeout,
	}
}

// NewGetUsersUsernameCollectionsCollectionSlugParamsWithContext creates a new GetUsersUsernameCollectionsCollectionSlugParams object
// with the ability to set a context for a request.
func NewGetUsersUsernameCollectionsCollectionSlugParamsWithContext(ctx context.Context) *GetUsersUsernameCollectionsCollectionSlugParams {
	return &GetUsersUsernameCollectionsCollectionSlugParams{
		Context: ctx,
	}
}

// NewGetUsersUsernameCollectionsCollectionSlugParamsWithHTTPClient creates a new GetUsersUsernameCollectionsCollectionSlugParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUsersUsernameCollectionsCollectionSlugParamsWithHTTPClient(client *http.Client) *GetUsersUsernameCollectionsCollectionSlugParams {
	return &GetUsersUsernameCollectionsCollectionSlugParams{
		HTTPClient: client,
	}
}

/* GetUsersUsernameCollectionsCollectionSlugParams contains all the parameters to send to the API endpoint
   for the get users username collections collection slug operation.

   Typically these are written to a http.Request.
*/
type GetUsersUsernameCollectionsCollectionSlugParams struct {

	/* CollectionSlug.

	   The collection slug name
	*/
	CollectionSlug string

	/* Page.

	   Page number. Default is 1
	*/
	Page *string

	/* PerPage.

	   Number of results per page. Default is 20
	*/
	PerPage *string

	/* Username.

	   The user's username
	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get users username collections collection slug params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUsersUsernameCollectionsCollectionSlugParams) WithDefaults() *GetUsersUsernameCollectionsCollectionSlugParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get users username collections collection slug params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUsersUsernameCollectionsCollectionSlugParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get users username collections collection slug params
func (o *GetUsersUsernameCollectionsCollectionSlugParams) WithTimeout(timeout time.Duration) *GetUsersUsernameCollectionsCollectionSlugParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get users username collections collection slug params
func (o *GetUsersUsernameCollectionsCollectionSlugParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get users username collections collection slug params
func (o *GetUsersUsernameCollectionsCollectionSlugParams) WithContext(ctx context.Context) *GetUsersUsernameCollectionsCollectionSlugParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get users username collections collection slug params
func (o *GetUsersUsernameCollectionsCollectionSlugParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get users username collections collection slug params
func (o *GetUsersUsernameCollectionsCollectionSlugParams) WithHTTPClient(client *http.Client) *GetUsersUsernameCollectionsCollectionSlugParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get users username collections collection slug params
func (o *GetUsersUsernameCollectionsCollectionSlugParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCollectionSlug adds the collectionSlug to the get users username collections collection slug params
func (o *GetUsersUsernameCollectionsCollectionSlugParams) WithCollectionSlug(collectionSlug string) *GetUsersUsernameCollectionsCollectionSlugParams {
	o.SetCollectionSlug(collectionSlug)
	return o
}

// SetCollectionSlug adds the collectionSlug to the get users username collections collection slug params
func (o *GetUsersUsernameCollectionsCollectionSlugParams) SetCollectionSlug(collectionSlug string) {
	o.CollectionSlug = collectionSlug
}

// WithPage adds the page to the get users username collections collection slug params
func (o *GetUsersUsernameCollectionsCollectionSlugParams) WithPage(page *string) *GetUsersUsernameCollectionsCollectionSlugParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get users username collections collection slug params
func (o *GetUsersUsernameCollectionsCollectionSlugParams) SetPage(page *string) {
	o.Page = page
}

// WithPerPage adds the perPage to the get users username collections collection slug params
func (o *GetUsersUsernameCollectionsCollectionSlugParams) WithPerPage(perPage *string) *GetUsersUsernameCollectionsCollectionSlugParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get users username collections collection slug params
func (o *GetUsersUsernameCollectionsCollectionSlugParams) SetPerPage(perPage *string) {
	o.PerPage = perPage
}

// WithUsername adds the username to the get users username collections collection slug params
func (o *GetUsersUsernameCollectionsCollectionSlugParams) WithUsername(username string) *GetUsersUsernameCollectionsCollectionSlugParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the get users username collections collection slug params
func (o *GetUsersUsernameCollectionsCollectionSlugParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *GetUsersUsernameCollectionsCollectionSlugParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param collection_slug
	if err := r.SetPathParam("collection_slug", o.CollectionSlug); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage string

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := qrPage
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PerPage != nil {

		// query param per_page
		var qrPerPage string

		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := qrPerPage
		if qPerPage != "" {

			if err := r.SetQueryParam("per_page", qPerPage); err != nil {
				return err
			}
		}
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
