// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUsersUsernameParams creates a new GetUsersUsernameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUsersUsernameParams() *GetUsersUsernameParams {
	return &GetUsersUsernameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUsersUsernameParamsWithTimeout creates a new GetUsersUsernameParams object
// with the ability to set a timeout on a request.
func NewGetUsersUsernameParamsWithTimeout(timeout time.Duration) *GetUsersUsernameParams {
	return &GetUsersUsernameParams{
		timeout: timeout,
	}
}

// NewGetUsersUsernameParamsWithContext creates a new GetUsersUsernameParams object
// with the ability to set a context for a request.
func NewGetUsersUsernameParamsWithContext(ctx context.Context) *GetUsersUsernameParams {
	return &GetUsersUsernameParams{
		Context: ctx,
	}
}

// NewGetUsersUsernameParamsWithHTTPClient creates a new GetUsersUsernameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUsersUsernameParamsWithHTTPClient(client *http.Client) *GetUsersUsernameParams {
	return &GetUsersUsernameParams{
		HTTPClient: client,
	}
}

/* GetUsersUsernameParams contains all the parameters to send to the API endpoint
   for the get users username operation.

   Typically these are written to a http.Request.
*/
type GetUsersUsernameParams struct {

	/* Username.

	   The user's username
	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get users username params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUsersUsernameParams) WithDefaults() *GetUsersUsernameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get users username params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUsersUsernameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get users username params
func (o *GetUsersUsernameParams) WithTimeout(timeout time.Duration) *GetUsersUsernameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get users username params
func (o *GetUsersUsernameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get users username params
func (o *GetUsersUsernameParams) WithContext(ctx context.Context) *GetUsersUsernameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get users username params
func (o *GetUsersUsernameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get users username params
func (o *GetUsersUsernameParams) WithHTTPClient(client *http.Client) *GetUsersUsernameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get users username params
func (o *GetUsersUsernameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUsername adds the username to the get users username params
func (o *GetUsersUsernameParams) WithUsername(username string) *GetUsersUsernameParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the get users username params
func (o *GetUsersUsernameParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *GetUsersUsernameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
