// Package dl provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.3 DO NOT EDIT.
package dl

// Object defines model for Object.
type Object struct {
	AbsoluteUrl   string       `json:"absolute_url"`
	Archives      *interface{} `json:"archives,omitempty"`
	DocumentNameS string       `json:"document_name_s"`
	DownloadUrl   string       `json:"download_url"`
	Id            int          `json:"id"`
	IsPrivate     bool         `json:"is_private"`
	IsPurchased   bool         `json:"is_purchased"`
	Name          string       `json:"name"`
	ObjImg        string       `json:"obj_img"`
	Price         struct {
		Currency *string `json:"currency,omitempty"`
		Symbol   string  `json:"symbol"`
		Value    float32 `json:"value"`
	} `json:"price"`
	ShowUrl         string                   `json:"show_url"`
	Type            string                   `json:"type"`
	UserCollections []map[string]interface{} `json:"user_collections"`
	UserImg         string                   `json:"user_img"`
	UserName        string                   `json:"user_name"`
	UserUrl         string                   `json:"user_url"`
	Username        string                   `json:"username"`
	Visits          int                      `json:"visits"`
	Wide            bool                     `json:"wide"`
}

// Objects defines model for Objects.
type Objects struct {
	Items      *[]Object `json:"items,omitempty"`
	TotalCount *int      `json:"total_count,omitempty"`
}

// Page defines model for Page.
type Page int

// GetPurchasesParams defines parameters for GetPurchases.
type GetPurchasesParams struct {
	Page *Page `json:"page,omitempty"`
}
