// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// File file
//
// swagger:model File
type File struct {

	// description
	Description string `json:"description,omitempty"`

	// Available ONLY with Oauth connected User. Not with API key.
	DownloadURL string `json:"download_url,omitempty"`

	// filename
	Filename string `json:"filename,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// size
	Size string `json:"size,omitempty"`

	// thumbnail url
	ThumbnailURL string `json:"thumbnail_url,omitempty"`
}

// Validate validates this file
func (m *File) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this file based on context it is used
func (m *File) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *File) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *File) UnmarshalBinary(b []byte) error {
	var res File
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
