// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImageUploadRequest image upload request
//
// swagger:model ImageUploadRequest
type ImageUploadRequest struct {

	// filename
	Filename string `json:"filename,omitempty"`

	// size
	Size int64 `json:"size,omitempty"`
}

// Validate validates this image upload request
func (m *ImageUploadRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this image upload request based on context it is used
func (m *ImageUploadRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImageUploadRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageUploadRequest) UnmarshalBinary(b []byte) error {
	var res ImageUploadRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
