// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImageUploadID image upload Id
//
// swagger:model ImageUploadId
type ImageUploadID struct {

	// filename
	Filename string `json:"filename,omitempty"`

	// upload id
	UploadID string `json:"upload_id,omitempty"`
}

// Validate validates this image upload Id
func (m *ImageUploadID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this image upload Id based on context it is used
func (m *ImageUploadID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImageUploadID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageUploadID) UnmarshalBinary(b []byte) error {
	var res ImageUploadID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
