// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Image image
//
// swagger:model Image
type Image struct {

	// id
	ID int64 `json:"id,omitempty"`

	// is primary
	IsPrimary bool `json:"is_primary,omitempty"`

	// original
	Original *ImageOriginal `json:"original,omitempty"`

	// standard
	Standard *ImageStandard `json:"standard,omitempty"`

	// thumbnail
	Thumbnail *ImageThumbnail `json:"thumbnail,omitempty"`
}

// Validate validates this image
func (m *Image) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOriginal(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStandard(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateThumbnail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Image) validateOriginal(formats strfmt.Registry) error {
	if swag.IsZero(m.Original) { // not required
		return nil
	}

	if m.Original != nil {
		if err := m.Original.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("original")
			}
			return err
		}
	}

	return nil
}

func (m *Image) validateStandard(formats strfmt.Registry) error {
	if swag.IsZero(m.Standard) { // not required
		return nil
	}

	if m.Standard != nil {
		if err := m.Standard.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("standard")
			}
			return err
		}
	}

	return nil
}

func (m *Image) validateThumbnail(formats strfmt.Registry) error {
	if swag.IsZero(m.Thumbnail) { // not required
		return nil
	}

	if m.Thumbnail != nil {
		if err := m.Thumbnail.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("thumbnail")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this image based on the context it is used
func (m *Image) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOriginal(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStandard(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateThumbnail(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Image) contextValidateOriginal(ctx context.Context, formats strfmt.Registry) error {

	if m.Original != nil {
		if err := m.Original.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("original")
			}
			return err
		}
	}

	return nil
}

func (m *Image) contextValidateStandard(ctx context.Context, formats strfmt.Registry) error {

	if m.Standard != nil {
		if err := m.Standard.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("standard")
			}
			return err
		}
	}

	return nil
}

func (m *Image) contextValidateThumbnail(ctx context.Context, formats strfmt.Registry) error {

	if m.Thumbnail != nil {
		if err := m.Thumbnail.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("thumbnail")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Image) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Image) UnmarshalBinary(b []byte) error {
	var res Image
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ImageOriginal image original
//
// swagger:model ImageOriginal
type ImageOriginal struct {

	// height
	Height string `json:"height,omitempty"`

	// url
	URL string `json:"url,omitempty"`

	// width
	Width string `json:"width,omitempty"`
}

// Validate validates this image original
func (m *ImageOriginal) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this image original based on context it is used
func (m *ImageOriginal) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImageOriginal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageOriginal) UnmarshalBinary(b []byte) error {
	var res ImageOriginal
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ImageStandard image standard
//
// swagger:model ImageStandard
type ImageStandard struct {

	// height
	Height string `json:"height,omitempty"`

	// url
	URL string `json:"url,omitempty"`

	// width
	Width string `json:"width,omitempty"`
}

// Validate validates this image standard
func (m *ImageStandard) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this image standard based on context it is used
func (m *ImageStandard) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImageStandard) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageStandard) UnmarshalBinary(b []byte) error {
	var res ImageStandard
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ImageThumbnail image thumbnail
//
// swagger:model ImageThumbnail
type ImageThumbnail struct {

	// height
	Height string `json:"height,omitempty"`

	// url
	URL string `json:"url,omitempty"`

	// width
	Width string `json:"width,omitempty"`
}

// Validate validates this image thumbnail
func (m *ImageThumbnail) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this image thumbnail based on context it is used
func (m *ImageThumbnail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImageThumbnail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageThumbnail) UnmarshalBinary(b []byte) error {
	var res ImageThumbnail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
