// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImageUploadStatus image upload status
//
// swagger:model ImageUploadStatus
type ImageUploadStatus struct {

	// filename
	Filename string `json:"filename,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// upload id
	UploadID string `json:"upload_id,omitempty"`
}

// Validate validates this image upload status
func (m *ImageUploadStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this image upload status based on context it is used
func (m *ImageUploadStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImageUploadStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageUploadStatus) UnmarshalBinary(b []byte) error {
	var res ImageUploadStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
