// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ObjectPatchMetadata object patch metadata
//
// swagger:model ObjectPatchMetadata
type ObjectPatchMetadata struct {

	// 2: Public, 0: Private
	Visibility *int64 `json:"visibility,omitempty"`
}

// Validate validates this object patch metadata
func (m *ObjectPatchMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this object patch metadata based on context it is used
func (m *ObjectPatchMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ObjectPatchMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ObjectPatchMetadata) UnmarshalBinary(b []byte) error {
	var res ObjectPatchMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
