// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostFileParams creates a new PostFileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostFileParams() *PostFileParams {
	return &PostFileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostFileParamsWithTimeout creates a new PostFileParams object
// with the ability to set a timeout on a request.
func NewPostFileParamsWithTimeout(timeout time.Duration) *PostFileParams {
	return &PostFileParams{
		timeout: timeout,
	}
}

// NewPostFileParamsWithContext creates a new PostFileParams object
// with the ability to set a context for a request.
func NewPostFileParamsWithContext(ctx context.Context) *PostFileParams {
	return &PostFileParams{
		Context: ctx,
	}
}

// NewPostFileParamsWithHTTPClient creates a new PostFileParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostFileParamsWithHTTPClient(client *http.Client) *PostFileParams {
	return &PostFileParams{
		HTTPClient: client,
	}
}

/* PostFileParams contains all the parameters to send to the API endpoint
   for the post file operation.

   Typically these are written to a http.Request.
*/
type PostFileParams struct {

	/* UploadID.

	   Temporary identifier to upload a file
	*/
	UploadID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostFileParams) WithDefaults() *PostFileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostFileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post file params
func (o *PostFileParams) WithTimeout(timeout time.Duration) *PostFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post file params
func (o *PostFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post file params
func (o *PostFileParams) WithContext(ctx context.Context) *PostFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post file params
func (o *PostFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post file params
func (o *PostFileParams) WithHTTPClient(client *http.Client) *PostFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post file params
func (o *PostFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUploadID adds the uploadID to the post file params
func (o *PostFileParams) WithUploadID(uploadID string) *PostFileParams {
	o.SetUploadID(uploadID)
	return o
}

// SetUploadID adds the uploadId to the post file params
func (o *PostFileParams) SetUploadID(uploadID string) {
	o.UploadID = uploadID
}

// WriteToRequest writes these params to a swagger request
func (o *PostFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param upload_id
	qrUploadID := o.UploadID
	qUploadID := qrUploadID
	if qUploadID != "" {

		if err := r.SetQueryParam("upload_id", qUploadID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
