// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostFileReader is a Reader for the PostFile structure.
type PostFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostFileCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostFileCreated creates a PostFileCreated with default headers values
func NewPostFileCreated() *PostFileCreated {
	return &PostFileCreated{}
}

/* PostFileCreated describes a response with status code 201, with default header values.

file created
*/
type PostFileCreated struct {
	Payload *PostFileCreatedBody
}

func (o *PostFileCreated) Error() string {
	return fmt.Sprintf("[POST /file][%d] postFileCreated  %+v", 201, o.Payload)
}
func (o *PostFileCreated) GetPayload() *PostFileCreatedBody {
	return o.Payload
}

func (o *PostFileCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostFileCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostFileCreatedBody post file created body
swagger:model PostFileCreatedBody
*/
type PostFileCreatedBody struct {

	// filename
	Filename string `json:"filename,omitempty"`
}

// Validate validates this post file created body
func (o *PostFileCreatedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post file created body based on context it is used
func (o *PostFileCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostFileCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostFileCreatedBody) UnmarshalBinary(b []byte) error {
	var res PostFileCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
