// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostImageParams creates a new PostImageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostImageParams() *PostImageParams {
	return &PostImageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostImageParamsWithTimeout creates a new PostImageParams object
// with the ability to set a timeout on a request.
func NewPostImageParamsWithTimeout(timeout time.Duration) *PostImageParams {
	return &PostImageParams{
		timeout: timeout,
	}
}

// NewPostImageParamsWithContext creates a new PostImageParams object
// with the ability to set a context for a request.
func NewPostImageParamsWithContext(ctx context.Context) *PostImageParams {
	return &PostImageParams{
		Context: ctx,
	}
}

// NewPostImageParamsWithHTTPClient creates a new PostImageParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostImageParamsWithHTTPClient(client *http.Client) *PostImageParams {
	return &PostImageParams{
		HTTPClient: client,
	}
}

/* PostImageParams contains all the parameters to send to the API endpoint
   for the post image operation.

   Typically these are written to a http.Request.
*/
type PostImageParams struct {

	/* UploadID.

	   Temporary identifier to upload a file
	*/
	UploadID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostImageParams) WithDefaults() *PostImageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostImageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post image params
func (o *PostImageParams) WithTimeout(timeout time.Duration) *PostImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post image params
func (o *PostImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post image params
func (o *PostImageParams) WithContext(ctx context.Context) *PostImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post image params
func (o *PostImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post image params
func (o *PostImageParams) WithHTTPClient(client *http.Client) *PostImageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post image params
func (o *PostImageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUploadID adds the uploadID to the post image params
func (o *PostImageParams) WithUploadID(uploadID string) *PostImageParams {
	o.SetUploadID(uploadID)
	return o
}

// SetUploadID adds the uploadId to the post image params
func (o *PostImageParams) SetUploadID(uploadID string) {
	o.UploadID = uploadID
}

// WriteToRequest writes these params to a swagger request
func (o *PostImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param upload_id
	qrUploadID := o.UploadID
	qUploadID := qrUploadID
	if qUploadID != "" {

		if err := r.SetQueryParam("upload_id", qUploadID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
